Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /contact/
Traceback (most recent call last):
  File "E:\TaiLieuBachKhoa\CNPM\IT3080_project-a192b08aa7f4389d37d104a091d91f67bbaa1607\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\TaiLieuBachKhoa\CNPM\IT3080_project-a192b08aa7f4389d37d104a091d91f67bbaa1607\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\TaiLieuBachKhoa\CNPM\IT3080_project-a192b08aa7f4389d37d104a091d91f67bbaa1607\nmcnpmapp\views.py", line 47, in contact
    return render(request, 'app/contact.html')
  File "E:\TaiLieuBachKhoa\CNPM\IT3080_project-a192b08aa7f4389d37d104a091d91f67bbaa1607\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\TaiLieuBachKhoa\CNPM\IT3080_project-a192b08aa7f4389d37d104a091d91f67bbaa1607\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\TaiLieuBachKhoa\CNPM\IT3080_project-a192b08aa7f4389d37d104a091d91f67bbaa1607\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: app/contact.html
